package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type example struct {
	ID             string `json:"id"`
	Title          string `json:"title"`
	Source         string `json:"source"`
	ExpectedSQL    string `json:"expectedSQL"`
	ExpectedParams []any  `json:"expectedParams"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	examples, err := loadExamples(filepath.Join(root, "docs-src", "examples.cue"))
	if err != nil {
		return err
	}
	if err := validateExamples(root, examples); err != nil {
		return err
	}

	output := filepath.Join(root, "docs", "generated", "examples.md")
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return err
	}
	return os.WriteFile(output, renderExamples(examples), 0o644)
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("could not find go.mod")
		}
		dir = parent
	}
}

func loadExamples(path string) ([]example, error) {
	cmd := exec.Command("cue", "export", path, "-e", "examples", "--out", "json")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("cue export %s: %w\n%s", path, err, strings.TrimSpace(string(output)))
	}

	var examples []example
	if err := json.Unmarshal(output, &examples); err != nil {
		return nil, err
	}
	return examples, nil
}

func validateExamples(root string, examples []example) error {
	seen := make(map[string]struct{}, len(examples))
	for _, example := range examples {
		if _, ok := seen[example.ID]; ok {
			return fmt.Errorf("duplicate docs example ID %q", example.ID)
		}
		seen[example.ID] = struct{}{}

		if !strings.HasPrefix(example.Source, "docs/examples/") {
			return fmt.Errorf("docs example %q source must be under docs/examples", example.ID)
		}
		if _, err := os.Stat(filepath.Join(root, example.Source)); err != nil {
			return fmt.Errorf("docs example %q source %q: %w", example.ID, example.Source, err)
		}
	}
	return nil
}

func renderExamples(examples []example) []byte {
	var buf bytes.Buffer
	buf.WriteString("# Examples\n\n")
	buf.WriteString("This page is generated by `go run ./cmd/docsgen`.\n\n")
	buf.WriteString("| ID | Title | Source |\n")
	buf.WriteString("| --- | --- | --- |\n")
	for _, example := range examples {
		source := strings.TrimPrefix(example.Source, "docs/")
		fmt.Fprintf(
			&buf,
			"| `%s` | %s | [`%s`](../%s) |\n",
			example.ID,
			example.Title,
			example.Source,
			source,
		)
	}
	return buf.Bytes()
}
